version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_agendamentos
    restart: always
    environment:
      POSTGRES_DB: agendamentos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  postgres_data:
